---
- name: pull docker mariadb image
  docker_image:
    name: mariadb
    tag: "{{ mariadb_version }}"

- name: start mariadb containers
  docker_container:
    name: "{{ mariadb_container_name }}"
    image: "docker.io/mariadb:{{ mariadb_version }}"
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
      - "0.0.0.0:{{ mysql_exposed_port }}:3306"
    volumes:
      - mysqlData:/var/lib/mysql
