---
- name: pull docker nginx image
  docker_image:
    name: nginx
    tag: "{{ nginx_version }}"

- name: ensure nginx conf dir exist
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: copy wordpress nginx config
  template:
    src: wordpress.conf.j2
    dest: /etc/nginx/conf.d/wordpress.conf

- name: start nginx containers
  docker_container:
    name: "{{ nginx_container_name }}"
    image: "docker.io/nginx:{{ nginx_version }}"
    state: started
    links:
      - "{{ wordpress_container_name }}:{{ wordpress_container_name }}"
    ports:
      - "0.0.0.0:{{ nginx_exposed_port }}:80"
    volumes:
      - /etc/nginx/conf.d/wordpress.conf:/etc/nginx/conf.d/default.conf
      - wordpressData:/var/www/html
